version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    networks:
      - net01
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  app:
    image: augustopimenta/count
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net01
    deploy:
      replicas: 3
    environment:
      - VIRTUAL_HOST=augusto.online

  networks:
    net01: