version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    networks:
      - main
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  manager:
    image: portainer/portainer
    networks:
      - main
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  main:
    external:
      name: main